export const countries = [
    { code: "AFG", displayName: "Afeganistão" },
    { code: "ALB", displayName: "Albânia" },
    { code: "DZA", displayName: "Argélia" },
    { code: "AND", displayName: "Andorra" },
    { code: "AGO", displayName: "Angola" },
    { code: "ATG", displayName: "Antígua e Barbuda" },
    { code: "ARG", displayName: "Argentina" },
    { code: "ARM", displayName: "Armênia" },
    { code: "AUS", displayName: "Austrália" },
    { code: "AUT", displayName: "Áustria" },
    { code: "AZE", displayName: "Azerbaijão" },
    { code: "BHS", displayName: "Bahamas" },
    { code: "BHR", displayName: "Bahrain" },
    { code: "BGD", displayName: "Bangladesh" },
    { code: "BRB", displayName: "Barbados" },
    { code: "BLR", displayName: "Bielorrússia" },
    { code: "BEL", displayName: "Bélgica" },
    { code: "BLZ", displayName: "Belize" },
    { code: "BEN", displayName: "Benin" },
    { code: "BTN", displayName: "Butão" },
    { code: "BOL", displayName: "Bolívia" },
    { code: "BOS", displayName: "Bósnia e Herzegovina" },
    { code: "BWA", displayName: "Botsuana" },
    { code: "BRA", displayName: "Brasil" },
    { code: "BRN", displayName: "Brunei" },
    { code: "BGR", displayName: "Bulgária" },
    { code: "BFA", displayName: "Burquina Faso" },
    { code: "BDI", displayName: "Burundi" },
    { code: "CPV", displayName: "Cabo Verde" },
    { code: "CAM", displayName: "Camboja" },
    { code: "CMR", displayName: "Camarões" },
    { code: "CAN", displayName: "Canadá" },
    { code: "CAF", displayName: "República Centro-Africana" },
    { code: "TCD", displayName: "Chade" },
    { code: "CHL", displayName: "Chile" },
    { code: "CHN", displayName: "China" },
    { code: "COL", displayName: "Colômbia" },
    { code: "COM", displayName: "Comores" },
    { code: "COG", displayName: "República do Congo" },
    { code: "COD", displayName: "República Democrática do Congo" },
    { code: "COK", displayName: "Ilhas Cook" },
    { code: "CRI", displayName: "Costa Rica" },
    { code: "CIV", displayName: "Costa do Marfim" },
    { code: "HRV", displayName: "Croácia" },
    { code: "CUB", displayName: "Cuba" },
    { code: "DNK", displayName: "Dinamarca" },
    { code: "DJI", displayName: "Djibuti" },
    { code: "DMA", displayName: "Dominica" },
    { code: "DOM", displayName: "República Dominicana" },
    { code: "EGY", displayName: "Egito" },
    { code: "SLV", displayName: "El Salvador" },
    { code: "GNQ", displayName: "Guiné Equatorial" },
    { code: "ERI", displayName: "Eritreia" },
    { code: "EST", displayName: "Estônia" },
    { code: "SWZ", displayName: "Eswatini" },
    { code: "ETH", displayName: "Etiópia" },
    { code: "FJI", displayName: "Fiji" },
    { code: "FRA", displayName: "França" },
    { code: "GAB", displayName: "Gabão" },
    { code: "GMB", displayName: "Gâmbia" },
    { code: "GEO", displayName: "Geórgia" },
    { code: "DEU", displayName: "Alemanha" },
    { code: "GHA", displayName: "Gana" },
    { code: "GRC", displayName: "Grécia" },
    { code: "GRD", displayName: "Granada" },
    { code: "GTM", displayName: "Guatemala" },
    { code: "GIN", displayName: "Guiné" },
    { code: "GNB", displayName: "Guiné-Bissau" },
    { code: "GUY", displayName: "Guiana" },
    { code: "HTI", displayName: "Haiti" },
    { code: "HND", displayName: "Honduras" },
    { code: "HUN", displayName: "Hungria" },
    { code: "ISL", displayName: "Islândia" },
    { code: "IND", displayName: "Índia" },
    { code: "IDN", displayName: "Indonésia" },
    { code: "IRN", displayName: "Irã" },
    { code: "IRQ", displayName: "Iraque" },
    { code: "IRL", displayName: "Irlanda" },
    { code: "ISR", displayName: "Israel" },
    { code: "ITA", displayName: "Itália" },
    { code: "JAM", displayName: "Jamaica" },
    { code: "JPN", displayName: "Japão" },
    { code: "JOR", displayName: "Jordânia" },
    { code: "KAZ", displayName: "Cazaquistão" },
    { code: "KEN", displayName: "Quênia" },
    { code: "KIR", displayName: "Quiribati" },
    { code: "KOR", displayName: "Coreia do Sul" },
    { code: "KWT", displayName: "Kuwait" },
    { code: "KGZ", displayName: "Quirguistão" },
    { code: "LAO", displayName: "Laos" },
    { code: "LVA", displayName: "Letônia" },
    { code: "LBN", displayName: "Líbano" },
    { code: "LSO", displayName: "Lesoto" },
    { code: "LIE", displayName: "Liechtenstein" },
    { code: "LTU", displayName: "Lituânia" },
    { code: "LUX", displayName: "Luxemburgo" },
    { code: "MDG", displayName: "Madagascar" },
    { code: "MWI", displayName: "Malawi" },
    { code: "MYS", displayName: "Malásia" },
    { code: "MDV", displayName: "Maldivas" },
    { code: "MEX", displayName: "México" },
    { code: "FSM", displayName: "Estados Federados da Micronésia" },
    { code: "MDA", displayName: "Moldávia" },
    { code: "MCO", displayName: "Mônaco" },
    { code: "MNG", displayName: "Montenegro" },
    { code: "MAR", displayName: "Marrocos" },
    { code: "MOZ", displayName: "Moçambique" },
    { code: "MMR", displayName: "Mianmar" },
    { code: "NAM", displayName: "Namíbia" },
    { code: "NRU", displayName: "Nauru" },
    { code: "NPL", displayName: "Nepal" },
    { code: "NLD", displayName: "Países Baixos" },
    { code: "NZL", displayName: "Nova Zelândia" },
    { code: "NIC", displayName: "Nicarágua" },
    { code: "NER", displayName: "Níger" },
    { code: "NGA", displayName: "Nigéria" },
    { code: "NOR", displayName: "Noruega" },
    { code: "OMN", displayName: "Omã" },
    { code: "PAK", displayName: "Paquistão" },
    { code: "PLW", displayName: "Palau" },
    { code: "PAN", displayName: "Panamá" },
    { code: "PNG", displayName: "Papua-Nova Guiné" },
    { code: "PRY", displayName: "Paraguai" },
    { code: "PER", displayName: "Peru" },
    { code: "PHL", displayName: "Filipinas" },
    { code: "POL", displayName: "Polônia" },
    { code: "PRT", displayName: "Portugal" },
    { code: "QAT", displayName: "Catar" },
    { code: "ROU", displayName: "Romênia" },
    { code: "RUS", displayName: "Rússia" },
    { code: "RWA", displayName: "Rwanda" },
    { code: "KNA", displayName: "São Cristóvão e Nevis" },
    { code: "LCA", displayName: "Santa Lúcia" },
    { code: "VCT", displayName: "São Vicente e Granadinas" },
    { code: "WSM", displayName: "Samoa" },
    { code: "SMR", displayName: "San Marino" },
    { code: "STP", displayName: "São Tomé e Príncipe" },
    { code: "SAU", displayName: "Arábia Saudita" },
    { code: "SEN", displayName: "Senegal" },
    { code: "SRB", displayName: "Sérvia" },
    { code: "SYC", displayName: "Seicheles" },
    { code: "SLE", displayName: "Serra Leoa" },
    { code: "SGP", displayName: "Cingapura" },
    { code: "SVK", displayName: "Eslováquia" },
    { code: "SVN", displayName: "Eslovênia" },
    { code: "SLB", displayName: "Solomon Islands" },
    { code: "SOM", displayName: "Somália" },
    { code: "ZAF", displayName: "África do Sul" },
    { code: "ESP", displayName: "Espanha" },
    { code: "LKA", displayName: "Sri Lanka" },
    { code: "SDN", displayName: "Sudão" },
    { code: "SUR", displayName: "Suriname" },
    { code: "SWE", displayName: "Suécia" },
    { code: "CHE", displayName: "Suíça" },
    { code: "SYR", displayName: "Síria" },
    { code: "TJK", displayName: "Tajiquistão" },
    { code: "TZA", displayName: "Tanzânia" },
    { code: "THA", displayName: "Tailândia" },
    { code: "TLS", displayName: "Timor-Leste" },
    { code: "TGO", displayName: "Togo" },
    { code: "TON", displayName: "Tonga" },
    { code: "TTO", displayName: "Trinidad e Tobago" },
    { code: "TUN", displayName: "Tunísia" },
    { code: "TUR", displayName: "Turquia" },
    { code: "TKM", displayName: "Turcomenistão" },
    { code: "TUV", displayName: "Tuvalu" },
    { code: "UGA", displayName: "Uganda" },
    { code: "UKR", displayName: "Ucrânia" },
    { code: "ARE", displayName: "Emirados Árabes Unidos" },
    { code: "GBR", displayName: "Reino Unido" },
    { code: "USA", displayName: "Estados Unidos" },
    { code: "URY", displayName: "Uruguai" },
    { code: "UZB", displayName: "Uzbequistão" },
    { code: "VUT", displayName: "Vanuatu" },
    { code: "VEN", displayName: "Venezuela" },
    { code: "VNM", displayName: "Vietnã" },
    { code: "YEM", displayName: "Iémen" },
    { code: "ZMB", displayName: "Zâmbia" },
    { code: "ZWE", displayName: "Zimbábue" },
];
